export type PanelId =
  | 'board'
  | 'approval'
  | 'report'
  | 'calendar'
  | 'meeting'
  | 'vehicle'
  | 'contacts'
  | 'documents'
  | 'certificate'
  | 'users'
  | 'roles'
  | 'boards'
  | 'approval-line'
  | 'common-code'
  | 'job-grade'
  | 'dept'
  | 'system'
  | 'settings'
  | 'menu-panel'
  | 'leave'
  | 'leave-req'
  | 'leave-req-form';

export type RpTab = 'home' | 'ai';
